-- ESTO CREA UNA BASE DE DATOS;
CREATE DATABASE Deportes;
-- SELECCION DE LA BASE DE DATOS CON LA QUE SE VA A TRABAJAR;
USE Deportes;

-- ESTO CREA UNA TABLA EN LA BASE DE DATOS
CREATE TABLE tiposDeporte(
id INT NOT NULL AUTO_INCREMENT, -- CLAVE PRIMARIA
nombreDeporte VARCHAR(50) NOT NULL,
balon VARCHAR(100) NOT NULL,
fechaInicioDeporte DATE NOT NULL, -- ESTO ES UN TIPO DATE(FECHA);
areaDeporte VARCHAR(100) NOT NULL,
mejorDeportista VARCHAR(50) NOT NULL,

PRIMARY KEY (id)); -- SE ESTABLECE LA CLAVE PRIMARIA
 
-- ESTO CREA UNA NUEVA COLUMNA EN LA TABLA EXISTENTE ;
ALTER TABLE tiposdeporte ADD COLUMN medallasObtenidas INT NOT NULL AFTER mejorDeportista;

-- ESTO BORRA UNA COLUMNA DE LA TABLA
ALTER TABLE tiposDeporte DROP COLUMN mejorDeportista;

-- ESTO CAMBIA EL TIPO DE DATO DE UNA COLUMNA
ALTER TABLE tiposDeporte MODIFY COLUMN balon INT NOT NULL;

-- ESTO BORRA TODA LA TABLA
DROP TABLE tiposDeporte;

-- ESTE COMANDO VERIFICA SI UNA TABLA EXISTE LA BORRA Y LA CREA DE NUEVO
DROP TABLE IF EXISTS tiposdeporte;
CREATE TABLE tiposDeporte(
id INT NOT NULL AUTO_INCREMENT, 
nombreDeporte VARCHAR(50) NOT NULL,
balon VARCHAR(100) NOT NULL,
fechaInicioDeporte DATE NOT NULL, 
areaDeporte VARCHAR(100) NOT NULL,
mejorDeportista VARCHAR(50) NOT NULL,

PRIMARY KEY (id));

-- ESTE COMANDO INSERTA DATOS EN LA TABLA
INSERT INTO tiposDeporte VALUES (1,'FUTBOL','MIKASA','2001-2-15','CESPED','MESSI');
-- ESTE COMANDO ACTUALIZA DATOS EN LA TABLA
UPDATE tiposDeporte SET areaDeporte = 'TIERRA' WHERE id=1;
 
-- ESTO ELIMINA TODOS LOS DATOS DE UNA TABLA;
TRUNCATE TABLE tiposDeporte;

-- ESTE COMANDO REALIZA CONSULTAS
SELECT id, nombreDeporte, balon from tiposDeporte;
 
-- ESTO UNE DOS COLUMNAS EN UNA SOLA
SELECT CONCAT(nombreDeporte,',', balon) as deporteBalon FROM tiposDeporte;